INSERT INTO tb_category (name, created_At) VALUES ('Books', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Electronics', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Computers', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Clothing', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Furniture', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Toys', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Home Appliances', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Jewelry', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Sports Equipment', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Beauty Products', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Kitchen Appliances', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Garden Supplies', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Healthcare', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Music Instruments', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Automotive', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Pet Supplies', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Stationery', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Movies', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Art and Crafts', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Footwear', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Bags and Luggage', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Fitness Equipment', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Watches', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Camping Gear', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Baby Products', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Party Supplies', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Appliances', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Shoes', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Handbags', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Jackets', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Watches', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Perfumes', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Cosmetics', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Headphones', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Smartphones', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Tablets', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Monitors', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Dresses', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Sunglasses', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Backpacks', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('T-shirts', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Sneakers', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Socks', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Skincare', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Toothbrushes', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Bicycles', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Hiking Gear', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Wine', NOW());
INSERT INTO tb_category (name, created_At) VALUES ('Drones', NOW());



